version: '3'
services:
  coredns: 
    image: coredns/coredns
    restart: always
    command: -conf /coredns-config/Corefile
    ports:
      - 53353:53/udp
    volumes:
      - ./coredns-config:/coredns-config/
